JuliaPlots/RecipesPipeline.jl

src/process_recipes.jl

remove :smooth handling

---

src/pipeline.jl

fix https://github.com/mkborregaard/RecipeUtils.jl/issues/6

add _recipe function stubs

---

Project.toml
src/RecipePipeline.jl
src/RecipeUtils.jl
src/pipeline.jl
src/process_recipes.jl
test/runtests.jl

Together with the companion PR in Plots, I managed to get the default grid displayed, but without the data.

Attempt to complete pipeline change

---

src/pipeline.jl
src/process_recipes.jl

This way, multiple recipe consumers can use the pipeline simultaneously.

Change the dispatch for `is_st_supported`

---

src/pipeline.jl
src/process_recipes.jl

Tune the defaults

---

Project.toml

This should help with the test failure here: https://travis-ci.org/github/JuliaPlots/Plots.jl/jobs/671297263?utm_medium=notification&utm_source=github_status
@daschw

Add compat for RecipesBase

---

.travis.yml

Add integration tests for Plots.jl

---

.github/workflows/docs.yml
README.md
docs/Project.toml
docs/make.jl
src/RecipesPipeline.jl
src/api.jl
src/group.jl
src/plot_recipe.jl
src/recipes.jl
src/series.jl
src/series_recipe.jl
src/type_recipe.jl
src/user_recipe.jl
src/utils.jl

This still needs the Documenter deploy key

Docs deployment

---

src/type_recipe.jl

https://github.com/JuliaPlots/Plots.jl/pull/2539 and https://github.com/JuliaPlots/Plots.jl/pull/2543

allow type recipes for `Number`s in arrays and surfaces

---

Project.toml
src/user_recipe.jl

fix plotting rowvector of functions

---

Project.toml
src/group.jl

fix grouping

---

.github/workflows/CI.yml
.travis.yml
Project.toml
test/makie.jl
test/runtests.jl

Rebased CI

---

src/api.jl

Might be related to https://github.com/JuliaPlots/Plots.jl/issues/2686

Fix split_attribute

---

Project.toml
src/recipes.jl

fix https://github.com/JuliaPlots/Plots.jl/issues/2666

fix time and period recipes

---

src/api.jl
src/type_recipe.jl

In preparation of https://github.com/JuliaPlots/Plots.jl/pull/2862

dispatch processing of axis args on the plot object

---

src/series.jl

fix https://github.com/JuliaPlots/RecipesPipeline.jl/issues/74
@oschulz can you check your histogram still works? The old hack wasn't ideal since users must be wrong by more than `1` in difference to get the warning, I thought it was too inconsistent.

refine friendly error

---

src/api.jl
src/plot_recipe.jl
src/series_recipe.jl
src/type_recipe.jl
src/user_recipe.jl
src/utils.jl

needs matching Plots changes
fixes https://github.com/JuliaPlots/Plots.jl/issues/3276

don't stringify argument to `warn_on_recipe_aliases!` early

---

src/utils.jl

For https://github.com/JuliaPlots/Plots.jl/pull/3612.

Add mesh3d for GR

---

Project.toml
src/plot_recipe.jl

Let's run it through CI first.
Ref: https://github.com/JuliaPlots/RecipesPipeline.jl/issues/100#issuecomment-908572482

Semver compat

---

src/utils.jl

Fixes https://github.com/JuliaPlots/RecipesPipeline.jl/issues/103

Avoid Vararg UnionAll dispatch

---

.github/workflows/CompatHelper.yml
Project.toml

This apparently had zero breaking changes since 0.3. cc @BeastyBlacksmith, @t-bltg

allow NanMath 1.0

---

src/RecipesPipeline.jl
src/utils.jl

To support changes in Plots.jl so that iteration can be restricted to explicit keys.

Add methods to access separate keysets of the DefaultsDict
